name: flutter_zoom_sdk
description: Zoom SDK from ZOOM ported to flutter as plugin with all necessary features and with Null Safety which is implementation by EvilRATT
version: 1.1.0+4
homepage: https://github.com/evilrat/flutter_zoom_sdk
repository: https://github.com/evilrat/flutter_zoom_sdk
issue_tracker: https://github.com/evilrat/flutter_zoom_sdk/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  js: ^0.6.3
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.evilratt.flutter_zoom_sdk
        pluginClass: FlutterZoomSdkPlugin
      ios:
        pluginClass: FlutterZoomSdkPlugin
      web:
        pluginClass: ZoomViewWeb
        fileName: flutter_zoom_web.dart